project:
  type: website
  output-dir: docs
#===============website======================
website:
  title: "Quarto"
  image: "quarto-dark-bg.jpeg"
  favicon: "favicon.png"
  google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://quarto.org
  repo-url: https://github.com/quarto-dev/quarto-web
  issue-url: https://github.com/quarto-dev/quarto-cli/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true

#===============pagefooter====================== 
  page-footer:
    background: dark
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        aria-label: Quarto Blog RSS 
    
#===============navbar======================      
  navbar:
    background: lightblue
    logo: quarto.png
    logo-alt: "Quarto logo"
    title: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: Overview
      - href: website/get-started/get-started.qmd
        text: "Get Started"
      - href: website/guide/guide.qmd
        text: "Guide"
      - href: website/extension/extensions.qmd
        text: "Extensions"
      - href: website/gallery/gallery.qmd
        text: "Gallery"
      - href: website/blog/blog.qmd
        text: "Blog"
      - about.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/quarto-dev/quarto-cli/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/quarto-dev/quarto-cli/discussions"        

    tools:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        text: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        text: Quarto GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        text: Quarto Blog RSS 
#===============siderbar====================== 
  sidebar:
    - id: get-started
      text: "Get Started"
      style: "floating"
      collapse-level: 2
      align: left
      background: light
      contents:
        - website/get-started/index.qmd
        - text: "first"
          href: website/get-started/get-started.qmd
        - text: "second"
          href: website/get-started/second.qmd
    
    - id: guide
      collapse-level: 1
      contents:
        - section: "Guide"
          href: website/guide/index.qmd
          contents:
          - section: "guide1"
            contents:
              - website/guide/guide.qmd






#===============format======================
format:
  html:
    theme:
      light: [cosmo, theme.scss]  
    css: styles.css
    toc: true



